# Generated by Django 3.2.25 on 2025-05-20 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group')], max_length=5)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='ArtistGroup',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artist_groups',
            },
        ),
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('station_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'radio_stations',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('isrc', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('file_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('total_hashes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fingerprinting.album')),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='RadioAirplayLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fingerprinting.radiostation')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fingerprinting.track')),
            ],
            options={
                'db_table': 'radio_airplay_logs',
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('fingerprint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash', models.CharField(db_index=True, max_length=255)),
                ('offset', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='fingerprinting.track')),
            ],
            options={
                'db_table': 'fingerprints',
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('audio_file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=20)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('storage_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fingerprinting.track')),
            ],
            options={
                'db_table': 'audio_files',
            },
        ),
        migrations.CreateModel(
            name='ArtistGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fingerprinting.artist')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fingerprinting.artistgroup')),
            ],
            options={
                'db_table': 'artist_group_members',
            },
        ),
        migrations.CreateModel(
            name='TrackArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fingerprinting.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fingerprinting.track')),
            ],
            options={
                'db_table': 'track_artists',
                'unique_together': {('track', 'artist')},
            },
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['file_hash'], name='tracks_file_ha_761e01_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['title'], name='tracks_title_f94b39_idx'),
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['hash'], name='fingerprint_hash_4baef9_idx'),
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['track', 'offset'], name='fingerprint_track_i_386eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['offset'], name='fingerprint_offset_d53179_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fingerprint',
            unique_together={('hash', 'track', 'offset')},
        ),
        migrations.AlterUniqueTogether(
            name='artistgroupmember',
            unique_together={('group', 'artist')},
        ),
    ]
