# Generated by Django 3.2.25 on 2025-05-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=255, unique=True)),
                ('total_hashes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=255)),
                ('offset', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='fingerprinting.song')),
            ],
            options={
                'db_table': 'fingerprints',
            },
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['hash'], name='fingerprint_hash_4baef9_idx'),
        ),
    ]
