# Generated by Django 3.2.25 on 2025-05-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprinting', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['song', 'offset'], name='fingerprint_song_id_305497_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['file_hash'], name='songs_file_ha_1581f7_idx'),
        ),
    ]
