# Generated by Django 3.2.25 on 2025-05-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprinting', '0002_auto_20250515_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fingerprint',
            unique_together={('hash', 'song', 'offset')},
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['offset'], name='fingerprint_offset_d53179_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['song_name'], name='songs_song_na_2a8800_idx'),
        ),
    ]
